name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install CD-Hit 
        run: |
          wget https://github.com/weizhongli/cdhit/releases/download/V4.8.1/cd-hit-v4.8.1-2019-0228.tar.gz
          tar -xzvf cd-hit-v4.8.1-2019-0228.tar.gz
          cd cd-hit-v4.8.1-2019-0228
          make
          chmod u+x cd-hit
      - name: Export cd-hit path
        run: |
          echo $HOME/cd-hit-v4.8.1-2019-0228 >> $GITHUB_PATH
      - name: Install rna-align 
        run: |
          wget https://zhanggroup.org/RNA-align/bin/RNAalign.tar.bz2
          tar -xvjf RNAalign.tar.bz2
          cd RNAalign
          g++ -O3 -ffast-math -o RNAalign RNAalign.cpp -static
          chmod u+x ./RNAalign
      - name: Export RNAalign path
        run: |
          echo $HOME/RNAalign >> $GITHUB_PATH
      - name: Test with pytest
        run: |
          echo $PATH
          which RNAalign
          which cd-hit
          pip install -r requirements.txt
          pip install coverage
          coverage run --source src/rnaglib -m pytest
          coverage report -m
          coverage xml
      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: pytest
          name: rnaglib 
          fail_ci_if_error: true
          verbose: true 
